name: MANUAL

on:
  workflow_dispatch:
  # push:
  #   tags:
  #     - "**"

jobs:
  NATIVE:
    runs-on: ubuntu-24.04
    steps:
      - name: Greeting
        run: echo "this job uses github-hosted runners"
      - name: Run container
        run: |
          docker run --rm hello-world:latest
      - name: Setup ssh agent
        uses: tanmancan/action-setup-ssh-agent-key@1.0.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      - name: Clone repository
        run: |
          git clone ${{ vars.REPO_URL }}
          ls -al
      - name: Build app
        run: |
          cd private-packages/golang-app
          go build -o main main.go
          ls -al
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: public-packages-artifact
          path: private-packages/golang-app/main
          retention-days: 2
      - name: Build container image
        run: |
          cd private-packages/golang-app
          docker build -f dockerfile .
          # docker build -f dockerfile --progress=plain .
